
connection.config.viettel-cloud.api-url= http://10.240.234.20:8095
connection.config.viettel-cloud.api-key=

connection.config.viettel-cloud-iam.api-url=https://iam.viettelcloud.vn

viettel.webhook.secret=whsec_.......

viettel-cloud.iam.client-id=

app.secret-key=rB7nJd9Gg4pVxQyWzK8LmNc2Hs3TfUuYvXaZbC1DeRg5ShTiJoLqMwNrPsQtRuSv
app.jwtAdminExpirationInMs=36000000

