spring.application.name=Viettel_cloud
connection.config.viettel-cloud.api-url= http://10.240.234.20:8095
connection.config.viettel-cloud.api-key=
viettel.webhook.secret=whsec_.......
base-url=https://iam.viettelcloud.vn/realms/viettel-cloud/protocol/openid-connect/auth
client-id=hmmm
redirect-uri=https://haizzzz.vn
