spring.application.name=Viettel_cloud

connection.config.viettel-cloud.api-url= http://10.240.234.20:8095
connection.config.viettel-cloud.api-key=
connection.config.viettel-cloud-iam.api-url=https://iam.viettelcloud.vn

viettel.webhook.secret=whsec_.......

viettel-cloud.iam.client-id=
viettel-cloud.iam.redirect-url=