spring.profiles.active=local

spring.datasource.url= jdbc:mysql://localhost:3306/viettel_cloud_sso?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true&autoReconnectForPools=true&autoReconnect=true&failOverReadOnly=false&characterEncoding=UTF-8&createDatabaseIfNotExist=true
spring.datasource.username= root
spring.datasource.password= root

connection.config.viettel-cloud.api-url= http://10.240.234.20:8095
connection.config.viettel-cloud.api-key=

connection.config.viettel-cloud-iam.api-url=https://iam.viettelcloud.vn

viettel.webhook.secret=whsec_.......

viettel-cloud.iam.client-id=

app.secret-key=rB7nJd.....
app.jwtAdminExpirationInMs=36000000
